# Generated by Django 3.0.6 on 2020-05-09 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('owner', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('GEN', 'General'), ('TEC', 'Technology'), ('SVC', 'Service'), ('MED', 'Media'), ('GAM', 'Games')], max_length=3)),
                ('status', models.CharField(choices=[('ON', 'Ongoing'), ('CM', 'Completed'), ('CA', 'Cancelled')], default='ON', max_length=2)),
                ('logo', models.ImageField(upload_to='logos')),
                ('video', models.URLField(blank=True)),
                ('deck', models.URLField(blank=True)),
            ],
        ),
    ]
