# Generated by Django 3.0.6 on 2020-05-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200509_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(upload_to='logos'),
        ),
    ]
