# Generated by Django 3.0.6 on 2020-05-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20200515_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='logo',
            field=models.ImageField(default='media/default_logos/project_default.png', upload_to='logos'),
        ),
    ]
