# Generated by Django 3.0.6 on 2020-05-28 21:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_auto_20200528_0457'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='join_requests',
            field=models.ManyToManyField(blank=True, related_name='requesting_join_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
