# Generated by Django 3.0.6 on 2020-06-03 04:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0013_auto_20200603_0435'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_projects', to=settings.AUTH_USER_MODEL),
        ),
    ]
